let joke =[
    `What did the horse say after it tripped?  Help! I’ve fallen and I can’t giddyup!    `,
    `Why can’t you hear a pterodactyl going to the bathroom?  Because the “P” is silent.    `,
    `What do you call a well-balanced horse?  Stable.  `,
    `What do you call an angry carrot?   A steamed veggie.  `,
    `Where do polar bears keep their money? In a snowbank.   `,
    `How do you make an egg-roll?    You push it!   `,
    `What would bears be without bees?    Ears.   `,
    `What do you call a pile of cats?    A meow-ntain.   `,
    `Why do cows wear bells? Because their horns don’t work.  `,
    `Why did the bicycle fall over?    Because it was two tired.   `,
    `What did the triangle say to the circle?   You’re pointless.  `,
    ` RIP, boiling water.   You will be mist.  `,
    ` Time flies like an arrow. Fruit flies like a banana.   `,
    ` I ordered a chicken and an egg online. I’ll let you know what comes first.  `,
    ` Why was Cinderella so bad at soccer?  She kept running away from the ball!  `,
    ` What do lawyers wear to court?    Lawsuits.   `,
    ` What do elves learn in school? The elf-abet.    `,
    ` Where was King David’s temple located?  Beside his ear.  `,
    ` What did one toilet say to another?    You look flushed.  `,
    ` What lights up a soccer stadium?   A soccer match.   `,
    ` What does corn say when it gets a compliment?   Aw, shucks! `,
    ` What’s the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle?`,
    ` What’s red and bad for your teeth?    A brick.   `,
    ` What do sprinters eat before they race? Nothing. They fast.  `,
    `  What has more lives than a cat?   A frog, because it croaks every day.   `,
    `  Why was the fish’s grades bad? They were below sea level.  `,
    `  What’s Forrest Gump’s password?    1forrest1. `,
    `  What do you call a fish without an eye?   Fsh.   `,
    `   Why shouldn't you use a broken pencil? Because it's pointless.  `,
    `   What do you call a pig that practices karate? A pork chop. `,
    `   What has four wheels and flies?   A garbage truck!  `,
    `What did the tomato say to the other tomato during a race? Ketchup.`,
    `Why shouldn’t you write with a broken pen?   Because it’s pointless.   `,
    `Why can't you trust the king of the jungle? Because he's always lion.`,
    `What did one wall say to the other? "I'll meet you at the corner."  `,
    `What do sea monsters eat?  Fish and ships.   `,
    `What do you call a sad strawberry? A blue berry!    `,
    `Why are pirates called pirates? They just ARRRR! `,
    ` How do you organize a space party?   You planet.    `,
    ` Why do seagulls fly over the sea?   If they flew over the bay, they would be bagels.   `,
    ` What do cows read the most?    Cattle-logs.   `,
    `  I lost an electron. You really have to keep an ion them! `,
    ` What do clouds wear under their shorts?  Thunder pants!    `,
    `  How many tickles does it take to make an octopus laugh? Ten-tickles. `,
    `What did 0 say to 8? "Nice belt." `,
    ` How did the hipster burn his tongue? He drank his coffee before it was cool.  `,
    ` What did the drummer name her twin daughters? Anna 1, Anna 2.  `,
    ` What did the lettuce say to the celery?   Quit stalking me!  `,
    ` What’s small and red and has a rough voice?   A hoarse raddish! `,
    ` Why do mushrooms get invited to all the parties?  Because they are such fungis. `,
    `  Why shouldn’t you tell secrets in a cornfield?   Too many ears. `,
    ` Why couldn’t the bad sailor learn the alphabet?  Because he always got lost at “C.”  `,
    ` What kind of cheese isn’t yours?    Nacho cheese.  `,
    `How does the moon cut his hair?  Eclipse it.  `,
    `What does a spy do when he is cold?    He goes undercover.`,
    `When do computers overheat?    When they need to vent.`,
    `Why did the scarecrow win an award?  Because he was outstanding in his fie`,
    `If athletes get athlete’s foot, what do elves get?    Mistle-toes.   `,
    `What’s brown and sticky?    Advertisement - Continue Reading Below  A stick. `,
    `What do you call a sad cup of coffee? Depresso.   `,
    `How did the telephone propose to his girlfriend?    He gave her a ring.`,
    `What did the cucumber say to the pickle? You mean a great dill to me.`,
    `Why didn't the melons get married?   Because they cantaloupe.  `,
    `Did you hear the rumor about butter?   Well, I'm not going to go spreading it!   `,
    `What happens when a snowman throws a tantrum?   He has a meltdown.`,
    `What goes up and down but doesn’t move?  Stairs.   `,
    `Why did the cookie go to the hospital? Because he felt crumby.  `,
    `What did the janitor say when he jumped out of the closet?    Supplies!   `,
    `What do you get when you cross a fish and an elephant? Swimming trunks. `,
    `What did the worker at the rubber band factory say when he was fired?    Oh snap.    `,
    `Why can’t a nose be 12 inches long? Because then it would be a foot. `,
    `Why did the belt go to jail? Because it held up a pair of pants.  `,
    `Where does the general put his armies?    In his sleevies.   `,
    `What do you call a magician that looses his magic?  Ian.  `,
    `Why did the golfer bring two pairs of pants?  In case he got a hole in one. `,
    `What did the yoga instructor say when her landlord tried to evict her?   Namaste.   `,
    `How do rabbits travel? By hareplanes.   `,
    `What do you call a sleeping dinosaur?  A dino-snore. `,
    `Why did the kid stock up on yeast?   He wanted to make some dough.  `,
    `What did the football coach say to the broken vending machine?      `,
    `Why are elephants wrinkly? Because you can’t iron them. `,
    `What did the cake say to the fork?   You want a piece of me?    `,
    `How did the two cats end their fight?   They hissed and made up.   `,
    `Why did the strawberry cry?    He found himself in a jam.  corny jokes`,
 `What’s black and white and read all over?   A newspaper!  `,
    `How did the barber win the race?   He knew a shortcut!    Advertisement - Continue Reading Bel`,
    `What did 50 Cent do when he was hungry?   58!   `,
    `What did the nut say to the other nut in a game of tag? Imma cashew!`,
    `Why did an old man fall in a well?   Because he couldn’t see that well!`,
    ` Why is Peter Pan always flying?  Because he Neverlands.   `,
    ` Why don’t astronomers like Orion’s Belt?    It’s a big waist of space. `,
    ` What do you call a hippie’s wife? Mississippi.`,
    ` Why are peppers the best at archery? Because they habanero!  `,
    ` How do you tell the difference between a bull and a cow?   It is either one or the udder! corny jokes`,
    ` What did one plate say to the other?  Dinner is on me! `,
    `Why do hummingbirds hum?  Because they don’t know the words!   `,
    `Why do cows have hooves and not feet?   They lactos`,
    `What do you call a chicken that is staring at a lettuce?  Chicken sees a salad.`,
    `What do you call a bear with no teeth?   A gummy bear!  `,
    `Which bear is the most condescending?    A pan-duh!  `,
    `Why are spiders so smart?    They can find everything on the web.    `,
    `What do you call a blind dinosaur? A do-you-think-he-saw-us.    `,
    `How do you make a water bed bouncier?  Add spring water. `,
    `What job did the frog have at the hotel?    Bellhop.    corny jokes`,
    `Advertisement - Continue Reading Below  `,
    `What kind of car does an egg drive?  A yolkswagen. `,
    `What kind of tea is hard to swallow?    Reality!    `,
    `Why wouldn't the shrimp share his treasure?    He was a little shellfish!  `,
    `Did you hear about the sensitive burglar?    He takes things personally! `,
    `When does a duck wake up?  At the quack of dawn!   `,
    ` What does a baby computer call his father?    Data!   `,
    `What do you get from a pampered cow?  Spoiled milk! `,
    `Why was the bee's hair always sticky?   He used a honeycomb.`,
    `What do you call phoney spaghetti?    An im-pasta.]`]

//     let a1 = confirm("Tell me a Joke?")
//     let c = true
//     while(c){
//     let b = joke[Math.floor(Math.random()*joke.length)]
//     let j = document.getElementById("joke")
//     j.innerHTML=b
//     let a = alert(b)
//     let c = confirm("Do you want another joke?")
//     if(c){
//         continue
//     }
//     else{
//         break;
//     }

// }
let b = joke[Math.floor(Math.random()*joke.length)]
let j = document.getElementById("joke")
j.innerHTML=b

